### ISSUE TITLE
Nest error message not being converted

### ISSUE THREAD

**Issue by davidmytton** [arcjet/arcjet-js#1376]
A user has reported the error value is not being converted correctly in a Nest.js wrapper they wrote around our SDK. They're seeing some errors logged as: `Encountered problem getting remote decision: %s` without the actual error.

They have a custom logger in the form:

```ts
export class ArcjetNestLogger extends Logger {
    info(msg: string, ...args: unknown[]): void;
    info(obj: Record<string, unknown>, msg?: string, ...args: unknown[]): void;
    info(...args: unknown[]): void {
        this.log(args);
    }
}
```

**Comment by blaine-arcjet** [comment]
I'm not sure what you are asking here. The `extends Logger` is obviously not from the `@arcjet/logger` package because we don't have a `.log()` function.

If they aren't using our logger, they need to handle all arguments and transform the data, as that happens in all of our logging functions.

**Comment by davidmytton** [comment]
Discussed this with @blaine-arcjet and the issue is the lack of string interpolation on the Winston format. We're going to test a fix for the args parsing by replacing

```ts
info(...args: unknown[]): void {
   this.log(args);
}
```

with 

```ts
info(...args: unknown[]): void {
    if (typeof args[0] === "string") {
        this.log("info", args[0], ...args.slice(1))
    } else {
        this.log("info", args[1], ...args.slice(2), args[0]);
    }
}
```
