### ISSUE TITLE
Show type warning if you provide allow and deny to detectBot 

### ISSUE THREAD

**Issue by davidmytton** [arcjet/arcjet-js#1502]
We throw if you provide both `allow` and `deny` configs for `detectBot`, but it would be helpful to show a type warning as well:

<img width="834" alt="image" src="https://github.com/user-attachments/assets/38c93aca-a6fd-4bbd-8650-80276be10eac">

```
file:///Users/david/Code/arcjet-js/arcjet/index.js:384
            throw new Error("Both allow and deny cannot be provided to detectBot");
                  ^

Error: Both allow and deny cannot be provided to detectBot
    at detectBot (file:///Users/david/Code/arcjet-js/arcjet/index.js:384:19)
    at file:///Users/david/Code/arcjet-js/examples/express-bots/index.js:17:5
    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)
```

**Comment by blaine-arcjet** [comment]
This is weird because there should be a type warning 🤔

**Comment by davidmytton** [comment]
Ah maybe because it's a js example, not ts?

**Comment by blaine-arcjet** [comment]
You can see that I needed to use `@ts-expect-error` when defining them both in the tests.

**Comment by blaine-arcjet** [comment]
Any example that runs in just Node without an explicit CLI tool to build the application is pure JS because otherwise adding a build step with all the dependencies takes away from the purity of the example. Perhaps we need to spend time on #72 so we can have consolidated examples.
