### ISSUE TITLE
Behavior of `validate` function on rules

### ISSUE THREAD

**Issue by blaine-arcjet** [arcjet/arcjet-js#1520]
Currently, only local rules have a `validate` function to ensure that the request is valid before we run `protect`. If `validate` throws, an `ArcjetErrorReason` is produced but we still send the request to the service, where it is validated again and rejected.

For remote-only rules, such as Rate Limit rules, we don't run validate at all and the rule gets rejected at the service.

Ideally, we'd run validate on all rules (local or remote). However, we need to decide if requests that fail any/all `validate` calls still get submitted to the service—I could see a reason for both yes and no.

**Comment by davidmytton** [comment]
We could validate, throw locally, but send a report containing the error for visibility?

**Comment by blaine-arcjet** [comment]
> We could validate, throw locally, but send a report containing the error for visibility?

Are you saying if **any single rule** does not pass validation, then we don't run **any rule**? That feels like it makes misconfiguration of rules very costly, as you lose all protection.

**Comment by davidmytton** [comment]
If we distinguish between runtime and "compile time" like you would in a compiled language then we can be more nuanced.

- Compile time = rule configured completely wrong e.g. both `allow` and `deny` for a botDetect. That should fail to run and is something you'd pick up on during development. Ideally TS will pick it up, but if you're using JS then you might not.
- Run time = a rule configured, but then missing some required property e.g. a rate limit on a header which isn't present. Is this the type you're referring to with the call to `validate`? For run time errors then we wouldn't want to have all rules fail to execute, just that one.

**Comment by blaine-arcjet** [comment]
Yes, you've broken down how I view the difference between SDK instantiation and protection.
* SDK Instantiation: Calling `arcjet()` or any rule constructor, such as `detectBot()` -  These validate the options passed in and throw if invalid so users can pick up on during development. Ideally TS will pick it up, but if you're using JS then you might not.
* Protection: We run the `validate()` function that checks for specific requirements in the request or (what we call) context.

This issue is describing "Protection".

**Comment by blaine-arcjet** [comment]
You said:

> For run time errors then we wouldn't want to have all rules fail to execute, just that one.

But how do you expect we handle this via the server? We can't skip sending the rule. We could change the protobuf to have `valid_rules` and `invalid_rules` so we can track them in the database and UI?

**Comment by blaine-arcjet** [comment]
Also assigning @e-moran since he'll be working on the validation stuff in the SDK and service as part of our pre-beta changes.

**Comment by blaine-arcjet** [comment]
This has been completed as of Alpha.28 - anything that is still an issue would be a bug and should be filed independently
