### ISSUE TITLE
Validate characteristics

### ISSUE THREAD

**Issue by blaine-arcjet** [arcjet/arcjet-js#1801]
If we fail to build a fingerprint from characteristics, we should immediately return an error decision saying the fingerprint could not be built.

This should happen before we build the fingerprint at the beginning of the `protect()` function.

**Comment by davidmytton** [comment]
It would be useful to have error codes or some way to check what the error was so different responses can be constructed depending on the error. For example if the user agent header is missing you might want to handle it differently from if the IP is missing (or some other custom header).

**Comment by blaine-arcjet** [comment]
> It would be useful to have error codes or some way to check what the error

Structured errors were brought up previously by @e-moran but I'm not sure if we captured it as an issue. I think that's a **very** large topic and project though.

**Comment by davidmytton** [comment]
Fair enough - doesn't need to be part of this issue.

**Comment by e-moran** [comment]
Yeah I brought it up [here](https://github.com/arcjet/arcjet-js/pull/1437#discussion_r1743828669). Didn't capture it as an issue at the time though, but I'll open one now.

**Comment by e-moran** [comment]
Opened an issue for it: https://github.com/arcjet/arcjet-js/issues/1855
