### ISSUE TITLE
Support plain objects for headers 

### ISSUE THREAD

**Issue by blaine-arcjet** [arcjet/arcjet-js#33]
The `ArcjetRequest` and `ArcjetRequestDetails` types currently limit the headers field to `Headers` because we usually work with the `ArcjetHeaders` abstraction; however, we might want to support records of headers being passed (possibly to support node's default `http.IncomingMessage`).

**Comment by davidgs** [comment]
Having the `http.IncomingHttpHeaders` would be super helpful, since that's what Node.js (and `express.js`) provide, and converting those to `Headers` is ... not fun.

**Comment by blaine-arcjet** [comment]
We actually provide the `ArcjetHeaders` utility which can be constructed by the IncomingHttpHeaders. Here's the implementation: https://github.com/arcjet/arcjet-js/blob/main/arcjet/index.ts#L538

We plan to provide a separate package for this in the future.
