### ISSUE TITLE
Skip remote call when `protect()` is called with no rules

### ISSUE THREAD

**Issue by blaine-arcjet** [arcjet/arcjet-js#607]
After the deprecation period for #605, we should make the case where a user calls `protect()` with no rules an error since it does nothing.

**Comment by davidmytton** [comment]
I'm wondering if there is a use case for this when you have ad-hoc rules. Say you wanted to apply a rate limit only to logged out users and [you're using our example from the docs](https://docs.arcjet.com/reference/nextjs#ad-hoc-rules), if you don't want to use Shield or other default rules and only want rate limits, this would prevent that use case.

Is there a reason we don't want to allow empty rules? Most commonly this might be a mistake, so our goal is to alert the developer. So perhaps this is a debug level log emit to let them know, but suppressed in prod (which usually defaults to a higher log level)?

**Comment by blaine-arcjet** [comment]
> Is there a reason we don't want to allow empty rules? 

My initial thinking is that users would be adding 100s of milliseconds onto each request for no reason because it calls Decide, but I think we could check for 0 rules and skip the remote call. This is also where the log would go.

**Comment by blaine-arcjet** [comment]
I'm going to close this. Due to the current architectural design of remote rules, we'll want to send a Decide request even if no rules are configured in the SDK.
