### ISSUE TITLE
Support for Deno

### ISSUE THREAD

**Issue by davidmytton** [arcjet/arcjet-js#758]
Allow us to support applications built with Deno.

**Comment by blaine-arcjet** [comment]
Blocked by https://github.com/denoland/deno/issues/24099

**Comment by davidmytton** [comment]
[Netlify Edge functions](https://docs.netlify.com/edge-functions/overview/) are based on Deno so if we want Next.js middleware to work on Netlify then we'll need Deno support.

**Comment by davidmytton** [comment]
https://github.com/denoland/deno/issues/24099 has been fixed in https://github.com/denoland/deno/pull/25606 so hopefully this will be in the next Deno release!

**Comment by blaine-arcjet** [comment]
> [Netlify Edge functions](https://docs.netlify.com/edge-functions/overview/) are based on Deno so if we want Next.js middleware to work on Netlify then we'll need Deno support.

This doesn't expose the `Deno.serve` mechanisms, so we'll need a separate adapter. Do you want to open an issue to support Netlify "Functions" and/or "Edge Functions" (that naming is very confusing).
