### ISSUE TITLE
Allow multiple withRule(s)

### ISSUE THREAD

**Issue by davidmytton** [arcjet/arcjet-js#927]
We added `withRule` in https://github.com/arcjet/arcjet-js/issues/193 to allow adding a new rule after the client is created, however it only allows a single new rule to be added. 

This would be useful in [our own example](https://docs.arcjet.com/reference/nextjs#ad-hoc-rules) where we change the rate limit for logged in users. We might also want to set a different bot detection rule at the same time e.g. disallow all automated clients for logged out, but allow API clients for logged in.

**Comment by blaine-arcjet** [comment]
`withRule` is allowed to be chained `aj.withRule(tokenBucket()).withRule(detectBot())`

I experimented with allowing multiple rules when I designed this and it makes the type inference very difficult or impossible so I think we just recommend multiple calls to `withRule`.

**Comment by davidmytton** [comment]
Updated the docs in https://github.com/arcjet/arcjet/pull/2345 to make this clear.
