### ISSUE TITLE
Unable to get client IP in Bun from alpha 14 onwards

### ISSUE THREAD

**Issue by davidmytton** [arcjet/arcjet-js#969]
The Bun example `examples/bun-rl` fails from alpha 14 onwards:

```
✦Aj ERROR Encountered problem getting remote decision: [failed_precondition] client IP not provided
```

**Comment by blaine-arcjet** [comment]
Localhost IP addresses are only allowed in development mode now. Bun doesn't set `NODE_ENV` for you like node does, so you need to set `ARCJET_ENV` in your environment file. I will update the `.env.local.example` files.
